CREATE TABLE `Academic`.`Student` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `student_code` VARCHAR(255) NOT NULL COMMENT '学号' ,
                                `student_name` VARCHAR(50) NOT NULL COMMENT '姓名' ,
                                `student_state` TINYINT NOT NULL COMMENT '状态' ,
                                `student_class` VARCHAR(50) NOT NULL COMMENT '班级' ,
                                `student_sex` TINYINT NOT NULL COMMENT '性别' ,
                                `idcard_num` VARCHAR(50) NOT NULL COMMENT '身份证号码' ,
                                `student_post` VARCHAR(50) NOT NULL COMMENT '职务' ,
                                `student_politicalstatus` VARCHAR(50) NOT NULL COMMENT '政治面貌' ,
                                `student_religion` VARCHAR(50) NOT NULL COMMENT '宗教信仰' ,
                                `student_nation` VARCHAR(15) NOT NULL COMMENT '民族' ,
                                `student_nativeplace` VARCHAR(15) NOT NULL COMMENT '籍贯' ,
                                `student_origin` VARCHAR(15) NOT NULL COMMENT '生源地' ,
                                `building_code` VARCHAR(255) NOT NULL COMMENT '楼号' ,
                                `dormitory_code` VARCHAR(255) NOT NULL COMMENT '寝室号' ,
                                `bed_code` VARCHAR(255) NOT NULL COMMENT '床号' ,
                                `student_tel` VARCHAR(50) NOT NULL COMMENT '联系电话' ,
                                `student_cornet` VARCHAR(50) NOT NULL COMMENT '短号' ,
                                `guardian_name` VARCHAR(50) NOT NULL COMMENT '监护人' ,
                                `guardian_tel` VARCHAR(50) NOT NULL COMMENT '监护人联系电话' ,
                                `student_address` VARCHAR(15) NOT NULL COMMENT '家庭住址' ,
                                `student_photo` VARCHAR(255) NOT NULL COMMENT '照片' ,
                                `remarks` VARCHAR(255) NOT NULL COMMENT '备注信息' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT UNSIGNED COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT UNSIGNED COMMENT '修改时间' ) ENGINE = InnoDB COMMENT = '学生信息表';

CREATE TABLE `Academic`.`User` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `user_code` VARCHAR(255) NOT NULL COMMENT '登录账号' ,
                                `user_pwd` VARCHAR(255) NOT NULL COMMENT '登录密码' ,
                                `user_name` VARCHAR(15) NOT NULL COMMENT '真实姓名' ,
                                `user_state` TINYINT NOT NULL COMMENT '状态' ,
                                `user_sex` TINYINT NOT NULL COMMENT '性别' ,
                                `user_section` VARCHAR(50) NOT NULL COMMENT '所属部门' ,
                                `user_class` VARCHAR(50) NOT NULL COMMENT '所属班级' ,
                                `user_type` TINYINT UNSIGNED NOT NULL COMMENT '用户类型' ,
                                `user_tel` VARCHAR(50) NOT NULL COMMENT '联系电话' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT UNSIGNED COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT UNSIGNED COMMENT '修改时间' ,
                                UNIQUE (`user_code`)) ENGINE = InnoDB COMMENT = '用户主表';

CREATE TABLE `Academic`.`Role` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `role_code` VARCHAR(255) NOT NULL COMMENT '角色编码' ,
                                `role_name` VARCHAR(50) NOT NULL COMMENT '角色名称' ,
                                `role_state` TINYINT NOT NULL COMMENT '状态' ,
                                `role_section` VARCHAR(50) NOT NULL COMMENT '所属部门' ,
                                `role_class` VARCHAR(50) NOT NULL COMMENT '所属班级' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT UNSIGNED COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT UNSIGNED COMMENT '修改时间' ,
                                UNIQUE (`role_code`)) ENGINE = InnoDB COMMENT = '角色表';

CREATE TABLE `Academic`.`School` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `school_name` varchar(50) NOT NULL COMMENT '学校名称' ,
                                `school_state` VARCHAR(15) NOT NULL COMMENT '状态' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT UNSIGNED COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT UNSIGNED COMMENT '修改时间' ,
                                UNIQUE (`school_code`)) ENGINE = InnoDB COMMENT = '学校表';

CREATE TABLE `Academic`.`Institude` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `institude_name` VARCHAR(50) NOT NULL COMMENT '学院名称' ,
                                `institude_state` TINYINT NOT NULL COMMENT '状态' ,
                                 `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT UNSIGNED COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT UNSIGNED COMMENT '修改时间' ,
                                UNIQUE (`institude_code`)) ENGINE = InnoDB COMMENT = '学院表';

CREATE TABLE `Academic`.`Subject` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `subject_code` VARCHAR(255) NOT NULL COMMENT '专业编码' ,
                                `subject_name` VARCHAR(50) NOT NULL COMMENT '专业名称' ,
                                `subject_state` TINYINT NOT NULL COMMENT '状态' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT UNSIGNED COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT UNSIGNED COMMENT '修改时间' ,
                                UNIQUE (`subject_code`)) ENGINE = InnoDB COMMENT = '专业表';

CREATE TABLE `Academic`.`Section` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                               `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `section_code` VARCHAR(255) NOT NULL COMMENT '部门编码' ,
                                `section_name` VARCHAR(50) NOT NULL COMMENT '部门名称' ,
                                `section_state` TINYINT NOT NULL COMMENT '状态' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT UNSIGNED COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT UNSIGNED COMMENT '修改时间' ,
                                UNIQUE (`section_code`)) ENGINE = InnoDB COMMENT = '部门表';

CREATE TABLE `Academic`.`Class` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `class_name` VARCHAR(50) NOT NULL COMMENT '班级名称' ,
                                `subject_code` VARCHAR(255) NOT NULL COMMENT '所属专业编码' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT UNSIGNED COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT UNSIGNED COMMENT '修改时间' ,
                                UNIQUE (`class_name`)) ENGINE = InnoDB COMMENT = '班级表';

CREATE TABLE `Academic`.`Dorm` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                               `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                               `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                               `building_code` VARCHAR(255) NOT NULL COMMENT '楼号' ,
                               `dormitory_code` VARCHAR(255) NOT NULL COMMENT '寝室号' ,
                               `bed_num` INT UNSIGNED NOT NULL COMMENT '床数' ,
                               `creater_name` VARCHAR(15) COMMENT '创建人' ,
                               `create_time` INT UNSIGNED COMMENT '创建时间' ,
                               `updater_name` VARCHAR(15) COMMENT '修改人' ,
                               `update_time` INT UNSIGNED COMMENT '修改时间' ) ENGINE = InnoDB COMMENT = '宿舍信息表';

CREATE TABLE `Academic`.`FundedProjects` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `projects_code` VARCHAR(255) NOT NULL COMMENT '项目编码' ,
                                `projects_name` VARCHAR(50) NOT NULL COMMENT '项目名称' ,
                                `projects_state` TINYINT NOT NULL COMMENT '项目状态' ,
                                `type_code` VARCHAR(255) NOT NULL COMMENT '类型编码' ,
                                `projects_type` TINYINT UNSIGNED NOT NULL COMMENT '项目类型' ,
                                `projects_deadline` INT UNSIGNED NOT NULL COMMENT '项目时限' ,
                                `projects_amount` decimal(15,2) NOT NULL COMMENT '项目金额' ,
                                `projects_introduction` TEXT NOT NULL COMMENT '项目简介' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT UNSIGNED COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT UNSIGNED COMMENT '修改时间' ) ENGINE = InnoDB COMMENT = '资助项目表';

／／新增
CREATE TABLE `Academic`.`Abnormal` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `abnormal_type` TINYINT UNSIGNED NOT NULL COMMENT '异动类型' ,
                                `abnormal_reason` VARCHAR(255) NOT NULL COMMENT '异动原因' ,
                                `abnormal_schoolyear` VARCHAR(255) NOT NULL COMMENT '异动学年' ,
                                `abnormal_semester` VARCHAR(255) NOT NULL COMMENT '异动学期' ,
                                `user_code` VARCHAR(255) NOT NULL COMMENT '人员编码' ,
                                `user_name` VARCHAR(15) NOT NULL COMMENT '人员名称' ,
                                `user_class` VARCHAR(50) NOT NULL COMMENT '原班级' ,
                                `user_class` VARCHAR(50) NOT NULL COMMENT '现班级' ,
                                `dormitory_code` VARCHAR(255) NOT NULL COMMENT '原寝室号' ,
                                `dormitory_code` VARCHAR(255) NOT NULL COMMENT '现寝室号' ,
                                `bed_code` VARCHAR(255) NOT NULL COMMENT '原床号' ,
                                `bed_code` VARCHAR(255) NOT NULL COMMENT '现床号' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT UNSIGNED COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT UNSIGNED COMMENT '修改时间' ,
                                UNIQUE (`user_code`)) ENGINE = InnoDB COMMENT = '异动信息表';

CREATE TABLE `Academic`.`Achievement` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `student_code` VARCHAR(255) NOT NULL COMMENT '学号' ,
                                `student_name` VARCHAR(50) NOT NULL COMMENT '姓名' ,
                                `student_state` TINYINT NOT NULL COMMENT '状态' ,
                                `achievement_schoolyear` VARCHAR(255) NOT NULL COMMENT '学年' ,
                                `achievement_semester` VARCHAR(255) NOT NULL COMMENT '学期' ,
                                `course_code` VARCHAR(255) NOT NULL COMMENT '课程编码' ,
                                `course_name` VARCHAR(50) NOT NULL COMMENT '课程名称' ,
                                `course_nature` TINYINT NOT NULL COMMENT '课程性质' ,
                                `student_credit` decimal(15,2) NOT NULL COMMENT '获得学分' ,
                                `student_gpa` decimal(15,2) NOT NULL COMMENT '获得绩点' ,
                                `student_zhengkaoscore` decimal(15,2) NOT NULL COMMENT '正考成绩' ,
                                `student_bukaoscore` decimal(15,2) NOT NULL COMMENT '补考成绩' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT UNSIGNED COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT UNSIGNED COMMENT '修改时间' ) ENGINE = InnoDB COMMENT = '学生成绩表';

CREATE TABLE `Academic`.`Leave` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `apply_type` TINYINT UNSIGNED NOT NULL COMMENT '申请类型' ,
                                `apply_code` VARCHAR(255) NOT NULL COMMENT '申请单号' ,
                                `apply_state` TINYINT NOT NULL COMMENT '状态' ,
                                `user_section` VARCHAR(255) NOT NULL COMMENT '部门' ,
                                `apply_num` INT UNSIGNED NOT NULL COMMENT '人数' ,
                                `apply_reason` VARCHAR(255) NOT NULL COMMENT '请假原因' ,
                                `apply_address` VARCHAR(255) NOT NULL COMMENT '前往地址' ,
                                `apply_leavetime` INT UNSIGNED NOT NULL COMMENT '请假起始时间' ,
                                `apply_backtime` INT UNSIGNED NOT NULL COMMENT '请假结束时间' ,
                                `apply_numberofdays` INT UNSIGNED NOT NULL COMMENT '请假天数' ,
                                `apply_numberofcourses` INT UNSIGNED NOT NULL COMMENT '请假节次' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT UNSIGNED COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT UNSIGNED COMMENT '修改时间' ) ENGINE = InnoDB COMMENT = '学生请假申请主表';

CREATE TABLE `Academic`.`Leave_1` (`GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `FID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '主表ID',
                                `student_code` VARCHAR(255) NOT NULL COMMENT '学号' ,
                                `student_name` VARCHAR(50) NOT NULL COMMENT '姓名' ,
                                `apply_enclosure` VARCHAR(255) NOT NULL COMMENT '附件' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT UNSIGNED COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT UNSIGNED COMMENT '修改时间' ) ENGINE = InnoDB COMMENT = '学生请假申请从表';
