CREATE TABLE `Academic`.`Student` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `student_code` VARCHAR(255) NOT NULL COMMENT '学号' ,
                                `student_name` VARCHAR(50) NOT NULL COMMENT '姓名' ,
                                `student_state` TINYINT NOT NULL COMMENT '状态' ,
                                `student_class` VARCHAR(50) NOT NULL COMMENT '班级' ,
                                `student_sex` TINYINT NOT NULL COMMENT '性别' ,
                                `idcard_num` VARCHAR(50) NOT NULL COMMENT '身份证号码' ,
                                `student_post` VARCHAR(50) NOT NULL COMMENT '职务' ,
                                `student_politicalstatus` VARCHAR(50) NOT NULL COMMENT '政治面貌' ,
                                `student_religion` VARCHAR(50) NOT NULL COMMENT '宗教信仰' ,
                                `student_nation` VARCHAR(15) NOT NULL COMMENT '民族' ,
                                `student_nativeplace` VARCHAR(15) NOT NULL COMMENT '籍贯' ,
                                `student_origin` VARCHAR(15) NOT NULL COMMENT '生源地' ,
                                `building_code` VARCHAR(255) NOT NULL COMMENT '楼号' ,
                                `dormitory_code` VARCHAR(255) NOT NULL COMMENT '寝室号' ,
                                `bed_code` VARCHAR(255) NOT NULL COMMENT '床号' ,
                                `student_tel` VARCHAR(50) NOT NULL COMMENT '联系电话' ,
                                `student_cornet` VARCHAR(50) NOT NULL COMMENT '短号' ,
                                `guardian_name` VARCHAR(50) NOT NULL COMMENT '监护人' ,
                                `guardian_tel` VARCHAR(50) NOT NULL COMMENT '监护人联系电话' ,
                                `student_address` VARCHAR(15) NOT NULL COMMENT '家庭住址' ,
                                `student_photo` VARCHAR(255) NOT NULL COMMENT '照片' ,
                                `remarks` VARCHAR(255) NOT NULL COMMENT '备注信息' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT COMMENT '修改时间' ) ENGINE = InnoDB COMMENT = '学生信息表';

CREATE TABLE `Academic`.`User` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `user_code` VARCHAR(255) NOT NULL COMMENT '登录账号' ,
                                `user_pwd` VARCHAR(255) NOT NULL COMMENT '登录密码' ,
                                `user_name` VARCHAR(15) NOT NULL COMMENT '真实姓名' ,
                                `user_state` TINYINT NOT NULL COMMENT '状态' ,
                                `user_sex` TINYINT NOT NULL COMMENT '性别' ,
                                `user_section` VARCHAR(50) NOT NULL COMMENT '所属部门' ,
                                `user_class` VARCHAR(50) NOT NULL COMMENT '所属班级' ,
                                `user_type` TINYINT UNSIGNED NOT NULL COMMENT '用户类型' ,
                                `user_tel` VARCHAR(50) NOT NULL COMMENT '联系电话' ,
                                `creater_name` VARCHAR(15) COMMENT '创建人' , 
                                `create_time` INT COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT COMMENT '修改时间' ,
                                UNIQUE (`user_code`)) ENGINE = InnoDB COMMENT = '用户主表';

CREATE TABLE `Academic`.`Role` ( `GUID` INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '唯一码' PRIMARY KEY,
                                `school_code` VARCHAR(255) NOT NULL COMMENT '学校编码' ,
                                `institude_code` VARCHAR(255) NOT NULL COMMENT '学院编码' ,
                                `role_code` VARCHAR(255) NOT NULL COMMENT '角色编码' ,
                                `role_name` VARCHAR(50) NOT NULL COMMENT '角色名称' ,
                                `role_state` TINYINT NOT NULL COMMENT '状态' ,
                                `role_section` VARCHAR(50) NOT NULL COMMENT '所属部门' ,
                                `role_class` VARCHAR(50) NOT NULL COMMENT '所属班级' ,
                                 `creater_name` VARCHAR(15) COMMENT '创建人' ,
                                `create_time` INT COMMENT '创建时间' ,
                                `updater_name` VARCHAR(15) COMMENT '修改人' ,
                                `update_time` INT COMMENT '修改时间' ,
                                UNIQUE (`role_code`)) ENGINE = InnoDB COMMENT = '角色表';